-- !Ups
ALTER TABLE Card ADD COLUMN name VARCHAR(100) NOT NULL;
ALTER TABLE Item DROP COLUMN name;
ALTER TABLE Hero DROP COLUMN name;
ALTER TABLE Monster DROP COLUMN name;
CREATE TABLE Weapon (
    card_id INTEGER PRIMARY KEY,
    light INTEGER NOT NULL,
    weight INTEGER NOT NULL,
    cost INTEGER NOT NULL,
    gold_value INTEGER NOT NULL,
    victory_points INTEGER NOT NULL
);
CREATE TABLE Spell (
    card_id INTEGER PRIMARY KEY,
    light INTEGER NOT NULL,
    cost INTEGER NOT NULL,
    victory_points INTEGER NOT NULL
);
CREATE TABLE Villager (
    card_id INTEGER PRIMARY KEY,
    cost INTEGER NOT NULL,
    gold_value INTEGER,
    victory_points INTEGER NOT NULL
);
ALTER TABLE Item DROP COLUMN weight;
ALTER TABLE Hero CHANGE COLUMN gold_value gold_value INTEGER;
-- !Downs
ALTER TABLE Card DROP COLUMN name;
ALTER TABLE Item ADD COLUMN name VARCHAR(100) NOT NULL;
ALTER TABLE Hero ADD COLUMN name VARCHAR(100) NOT NULL;
ALTER TABLE Monster ADD COLUMN name VARCHAR(100) NOT NULL;
DROP TABLE Weapon;
DROP TABLE Villager;
DROP TABLE Spell;
ALTER TABLE Item ADD COLUMN weight INTEGER;
ALTER TABLE Item CHANGE COLUMN gold_value gold_value INTEGER NOT NULL;
ALTER TABLE Hero CHANGE COLUMN gold_value gold_value INTEGER NOT NULL;
